bug: generic inner records don't seem to work

When a generic class contains a generic inner record, resolution of a
constructor to that record fails.  Changing the inner record to a
class, or moving the record outside of the class works.  The error
message suggests that the cause of failure is due to a mismatch in
supplying 'outer' to the constructor call.  It's not clear to me
whether the fix would be to add the 'outer' argument to the
constructor's formals or to remove it from the actual's argument list.

Here's the error message:

innerRecord.chpl:5: In function 'chpl__initCopy':
innerRecord.chpl:5: error: unresolved call 'B(T=type int(64), v=int(64), c=int(64), outer=A(int(64)))'
innerRecord.chpl:5: note: candidates are: B(_mt: _MT, outer: A, type T, v: T, c)
